---

- name: Create Virtual Machine
  hosts: pve
  roles:
  - vm-templates

- name: Create Virtual Machine
  hosts: localhost 
  roles:
  - vm-creation


- name: Check of all vms are up
  hosts: vms
  gather_facts: no
  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 100

- name: Deploy k3s on Vms
  hosts: k3s_cluster 
  become: yes
  become_user: root 
  roles:
  - k3s-install
  - configure-kubectl

