---

- name: Create Virtual Machine
  hosts: localhost 
  roles:
  - vm-creation
  tags: vms

- name: Check of all vms are up
  hosts: vms
  gather_facts: no
  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 100
  - name: Copy host file to virtual machines
    become: yes
    copy:
      src: /etc/hosts
      dest: /etc/hosts
  tags: vms

- name: Deploy k3s on Vms
  hosts: k3s_cluster 
  become: yes
  become_user: root 
  roles:
  - k3s-install
  - configure-kubectl
  tags: k3s
