---

- name: Set k3s installation state to uninstall 
  hosts: k3s_cluster
  tasks: 
  - set_fact: k3s_state="uninstalled"

- name: Cleanup k3s on vms
  hosts: k3s_cluster
  become: yes
  become_user: root
  roles:
  - k3s-install

- name: Destroy virtual machines 
  hosts: localhost
  roles:
  - vm-destruction

