---

- name: Create Virtual Machine
  hosts: localhost
  roles:
  - vm-creation 

- name: Check of all vms are up
  hosts: vms
  tasks: 
  - name: Wait for system to become reachable 
    wait_for_connection:
      timeout: 900
      delay: 20
    retries: 10
    delegate_to: localhost

- name: Deploy k3s on Vms
  hosts: k3s_cluster 
  become: yes
  become_user: root 
  roles:
  - k3s-install
  - configure-kubectl

