---

- name: Set k3s installation state to uninstall 
  hosts: k3s_cluster
  tasks: 
  - set_fact: k3s_state="stopped"

- name: Stop K3S
  hosts: k3s_cluster
  become: yes
  become_user: root
  roles:
  - k3s-install

